let cssQueDB = [
    {
        question: "A pump can fill a tank with water in 2 hours. Because of a leak, it took 2 hours to fill the tank. The leak can drain all the water of the tank in:",
        a: "4 1/3 hours",
        b: "7 hours",
        c: "8 hours",
        d: "14 hours",
        ans: "ans4",
    },
    {
        question: "Pipes A and B can fill a tank in 5 and 6 hours respectively. Pipe C can empty it in 12 hours. If all the three pipes are opened together, then the tank will be filled in:",
        a: "1 13/17 hours",
        b: "2 8/11 hours",
        c: "3 9/17 hours",
        d: "4 1/2 hours",
        ans: "ans3",
    },
    {
        question: "Two pipes A and B can fill a cistern in 37 minutes and 45 minutes respectively. Both pipes are opened. The cistern will be filled in just half an hour, if the B is turned off after:",
        a:"15 min",
        b: "5 min",
        c: "9 min",
        d: "10 min",
        ans: "ans3",
    },
    {
        question: "Two pipes can fill a tank in 20 and 24 minutes respectively and a waste pipe can empty 3 gallons per minute. All the three pipes working together can fill the tank in 15 minutes. The capacity of the tank is:",
        a: " 60 gallons ",
        b: " 100 gallons ",
        c: " 120 gallons ",
        d: " 180 gallons ",
        ans: "ans3",
    },
    {
        question: "Three pipes A, B and C can fill a tank in 6 hours. After working at it together for 2 hours, C is closed and A and B can fill the remaining part in 7 hours. The number of hours taken by C alone to fill the tank is:",
        a: "10",
        b: "12",
        c: "14",
        d: "16",
        ans: "ans3",
    },
    {
        question: "A tank is filled in 5 hours by three pipes A, B and C. The pipe C is twice as fast as B and B is twice as fast as A. How much time will pipe A alone take to fill the tank?",
        a: "20 hours",
        b: "25 hours",
        c: "35 hours",
        d: "cannot be determined",
        ans: "ans3",
    },
    {
        question: "Two pipes A and B together can fill a cistern in 4 hours. Had they been opened separately, then B would have taken 6 hours more than A to fill the cistern. How much time will be taken by A to fill the cistern separately?",
        a: "1 hour",
        b: "2 hours",
        c: "6 hours",
        d: "8 hours",
        ans: "ans3",
    },
    {
        question: "Two pipes A and B can fill a tank in 20 and 30 minutes respectively. If both the pipes are used together, then how long will it take to fill the tank?",
        a: "12 min",
        b: "15 min",
        c: "25 min",
        d: "50 min",
        ans: "ans1",
    },
    {
        question: "Two pipes A and B can fill a tank in 15 minutes and 20 minutes respectively. Both the pipes are opened together but after 4 minutes, pipe A is turned off. What is the total time required to fill the tank?",
        a: "10 min 20 sec",
        b: "11 min 45 sec",
        c: "12 min 30 sec",
        d: "14 min 40 sec",
        ans: "ans4",
    },
    {
        question: "One pipe can fill a tank three times as fast as another pipe. If together the two pipes can fill the tank in 36 minutes, then the slower pipe alone will be able to fill the tank in:",
        a: "81 min",
        b: "108 min",
        c: "144 min",
        d: "192 min",
        ans: "ans3",
    }
];



let htmlQueDB = [
    {
        question: "A train running at the speed of 60 km/hr crosses a pole in 9 seconds. What is the length of the train?",
        a: "120 metres",
        b: "180 metres",
        c: "324 metres",
        d: "150 metres",
        ans: "ans4",
    },
    {
        question: "A train 125 m long passes a man, running at 5 km/hr in the same direction in which the train is going, in 10 seconds. The speed of the train is:",
        a: " 45 km/hr ",
        b: " 50",
        c: " 54 ",
        d: " 55 ",
        ans: "ans2",
    },
    {
        question: "The length of the bridge, which a train 130 metres long and travelling at 45 km/hr can cross in 30 seconds, is:",
        a: "200 m",
        b: "225 m",
        c: "245 m",
        d: "250 m",
        ans: "ans3",
    },
    {
        question: "Two trains running in opposite directions cross a man standing on the platform in 27 seconds and 17 seconds respectively and they cross each other in 23 seconds. The ratio of their speeds is:",
        a: "1 :3",
        b: "3:2",
        c: "3:4",
        d: "None of these",
        ans: "ans2",
    },
    {
        question: "A train passes a station platform in 36 seconds and a man standing on the platform in 20 seconds. If the speed of the train is 54 km/hr, what is the length of the platform?",
        a: "None of these",
        b: "120 m",
        c: "240 m",
        d: "300 m",
        ans: "ans4",
    },
    {
        question: " A train 240 m long passes a pole in 24 seconds. How long will it take to pass a platform 650 m long?",
        a: "65 sec",
        b: "89 sec",
        c: "100 sec",
        d: "150 sec",
        ans: "ans2",
    },
    {
        question: "Two trains of equal length are running on parallel lines in the same direction at 46 km/hr and 36 km/hr. The faster train passes the slower train in 36 seconds. The length of each train is:",
        a: "50 m",
        b: "72 m",
        c: "80 m",
        d: "82 m",
        ans: "ans1",
    },
    {
        question: " A train 360 m long is running at a speed of 45 km/hr. In what time will it pass a bridge 140 m long?",
        a: "40 sec",
        b: "42 sec",
        c: "45 sec",
        d: "48 sec",
        ans: "ans1",
    },
    {
        question: "Two trains are moving in opposite directions @ 60 km/hr and 90 km/hr. Their lengths are 1.10 km and 0.9 km respectively. The time taken by the slower train to cross the faster train in seconds is:",
        a: "36",
        b: "45",
        c: "48",
        d: "49",
        ans: "ans3",
    },
    {
        question: "	A jogger running at 9 kmph alongside a railway track in 240 metres ahead of the engine of a 120 metres long train running at 45 kmph in the same direction. In how much time will the train pass the jogger?",
        a: "3.6 sec",
        b: "18 sec",
        c: "36 sec",
        d: "72 sec",
        ans: "ans3",  
    }
    
];

let jsQueDB = [
    {
        question: " Alfred buys an old scooter for Rs. 4700 and spends Rs. 800 on its repairs. If he sells the scooter for Rs. 5800, his gain percent is:",
        a: "4 4/7 %",
        b: "5 5/11 %",
        c: "10%",
        d: "12%",
        ans: "ans2",
    },
    {
        question: "The cost price of 20 articles is the same as the selling price of x articles. If the profit is 25%, then the value of x is:",
        a: "15",
        b: "16",
        c: "18",
        d: "25",
        ans: "ans2",
    },
    {
        question: "If selling price is doubled, the profit triples. Find the profit percent.?",
        a: "66 2/3",
        b: "100",
        c: "105 1/3",
        d: "120",
        ans: "ans2",
    },
    {
        question: "In a certain store, the profit is 320% of the cost. If the cost increases by 25% but the selling price remains constant, approximately what percentage of the selling price is the profit?",
        a: "30%",
        b: "70%",
        c: "100%",
        d: "250%",
        ans: "ans2",
    },
    {
        question: "A vendor bought toffees at 6 for a rupee. How many for a rupee must he sell to gain 20%?",
        a: "3",
        b: "4",
        c: "5",
        d: "6",
        ans: "ans3",
    },
    {
        question: "The percentage profit earned by selling an article for Rs. 1920 is equal to the percentage loss incurred by selling the same article for Rs. 1280. At what price should the article be sold to make 25% profit?",
        a: "Rs.2000",
        b: "Rs.2200",
        c: "Rs.2400",
        d: "Data inadequate",
        ans: "ans1",
    },
    {
        question: "A shopkeeper expects a gain of 22.5% on his cost price. If in a week, his sale was of Rs. 392, what was his profit?",
        a: "Rs.18.20",
        b: "Rs.70",
        c: "Rs.72",
        d: "Rs.88.25",
        ans: "ans3",
    },
    {
        question: "A man buys a cycle for Rs. 1400 and sells it at a loss of 15%. What is the selling price of the cycle?",
        a: "Rs.1090",
        b: "Rs.1160",
        c: "Rs.1190",
        d: "Rs.1202",
        ans: "ans3",
    },
    {
        question: "Sam purchased 20 dozens of toys at the rate of Rs. 375 per dozen. He sold each one of them at the rate of Rs. 33. What was his percentage profit?",
        a: "3.5",
        b: "4.5",
        c: "5.6",
        d: "6.5",
        ans: "ans3",
    },
    {
        question: "Some articles were bought at 6 articles for Rs. 5 and sold at 5 articles for Rs. 6. Gain percent is:",
        a: "30%",
        b: "33 1/3%",
        c: "35%",
        d: "44%",
        ans: "ans4",
    }
];


let pythonQueDB = [
    {
        question: "A batsman scored 110 runs which included 3 boundaries and 8 sixes. What percent of his total score did he make by running between the wickets?",
        a: "45%",
        b: "45 5/11%",
        c: "54 6/11%",
        d: "55%",
        ans: "ans2",
    },
    {
        question: "Two students appeared at an examination. One of them secured 9 marks more than the other and his marks was 56% of the sum of their marks. The marks obtained by them are:",
        a: " 39, 30 ",
        b: " 41, 32",
        c: " 42, 33 ",
        d: " 43, 34",
        ans: "ans3",
    },
    {
        question: " A fruit seller had some apples. He sells 40% apples and still has 420 apples. Originally, he had:",
        a: "588 apples",
        b: "600 apples",
        c: "672 apples",
        d: "700 apples",
        ans: "ans4",
    },
    {
        question: "What percentage of numbers from 1 to 70 have 1 or 9 in the unit's digit?",
        a: "1",
        b: "14",
        c: "20",
        d: "21",
        ans: "ans3",
    },
    {
        question: "If A = x% of y and B = y% of x, then which of the following is true?",
        a: "A is smaller than B",
        b: "A is grater than B",
        c: "A=B",
        d: "cannot be determined",
        ans: "ans3",
    },
    {
        question: "If 20% of a = b, then b% of 20 is the same as:",
        a: "4% of a",
        b: "5% of a",
        c: "20% of a",
        d: "None of these",
        ans: "ans1",
    },
    {
        question: "In a certain school, 20% of students are below 8 years of age. The number of students above 8 years of age is  of the number of students of 8 years of age which is 48. What is the total number of students in the school?",
        a: "72",
        b: "80",
        c: "120",
        d: "100",
        ans: "ans4",
    },
    {
        question: "Two numbers A and B are such that the sum of 5% of A and 4% of B is two-third of the sum of 6% of A and 8% of B. Find the ratio of A : B",
        a: "2:3",
        b: "1:1",
        c: "3:4",
        d: "4:3",
        ans: "ans4",
    },
    {
        question: "A student multiplied a number by	3/5	instead of	5/3. What is the percentage error in the calculation?",
        a: "34%",
        b: "44%",
        c: "54%",
        d: "64%",
        ans: "ans4",
    },
    {
        question: "In an election between two candidates, one got 55% of the total valid votes, 20% of the votes were invalid. If the total number of votes was 7500, the number of valid votes that the other candidate got, was:",
        a: "2700",
        b: "2900",
        c: "3000",
        d: "3100",
        ans: "ans1",
    }
];